- job:
    name: gceapi-functional-neutron
    parent: legacy-dsvm-base
    run: playbooks/functional-neutron-dsvm-gceapi/run.yaml
    post-run: playbooks/functional-neutron-dsvm-gceapi/post.yaml
    timeout: 7500
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/gce-api
      - openstack/neutron

- project:
    check:
      jobs:
        - gceapi-functional-neutron:
            voting: false
